# -*- coding: utf-8 -*-
import time
import traceback

# Form implementation generated from reading ui file '.\ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtGui import QIcon, QMovie

from pages import new_user, selector_page
from threads import bdQueryLogin
from utils import broadcast


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1207, 762)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("background-color: #ffc600;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.page)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setMaximumSize(QtCore.QSize(609, 16777215))
        self.widget_4.setStyleSheet("QWidget {\n"
"          \n"
"            background-color:rgb(255, 226, 127);\n"
"            color: #ffffff;\n"
"            padding: 8px;\n"
"            border-radius:20px;\n"
"        }")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        self.widget_6.setStyleSheet("QWidget {\n"
"          \n"
"            background-color:#92653c;\n"
"            color: #ffffff;\n"
"            padding: 8px;\n"
"            border-radius:20px;\n"
"        }")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_2.setContentsMargins(50, -1, 50, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_6)
        self.label_2.setMinimumSize(QtCore.QSize(0, 47))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 47))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.widget_25 = QtWidgets.QWidget(self.widget_6)
        self.widget_25.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_25.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_25.setObjectName("widget_25")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_25)
        self.horizontalLayout_20.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_20.setSpacing(3)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.config_label = QtWidgets.QLabel(self.widget_25)
        self.config_label.setMinimumSize(QtCore.QSize(100, 35))
        self.config_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.config_label.setStyleSheet("QLabel {\n"
"            background-color:#612d26;\n"
"            font-weight: bold;\n"
"            color: rgb(255, 255, 255);\n"
"            padding: 3px;\n"
"            border-radius: 4px;\n"
"        }")
        self.config_label.setObjectName("config_label")
        self.horizontalLayout_20.addWidget(self.config_label)
        self.user = QtWidgets.QLineEdit(self.widget_25)
        self.user.setMinimumSize(QtCore.QSize(300, 35))
        self.user.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.user.setStyleSheet("QLineEdit {\n"
"            background-color: #f0f0f0;\n"
"            border: none;\n"
"            padding: 2px;\n"
"            border-radius: 4px;\n"
"            color: #333;\n"
"            font-size:13px\n"
"        }\n"
"\n"
"        QLineEdit:hover {\n"
"            background-color: #e0e0e0;\n"
"        }\n"
"\n"
"        QLineEdit:focus {\n"
"            background-color: #ffffff;\n"
"            border: 2px solid #007bff;\n"
"        }")
        self.user.setObjectName("user")
        self.horizontalLayout_20.addWidget(self.user)
        self.verticalLayout_2.addWidget(self.widget_25)
        self.widget_26 = QtWidgets.QWidget(self.widget_6)
        self.widget_26.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_26.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_26)
        self.horizontalLayout_21.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_21.setSpacing(3)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.config_label_2 = QtWidgets.QLabel(self.widget_26)
        self.config_label_2.setMinimumSize(QtCore.QSize(100, 35))
        self.config_label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.config_label_2.setStyleSheet("QLabel {\n"
"            background-color:#612d26;\n"
"            font-weight: bold;\n"
"            color: rgb(255, 255, 255);\n"
"            padding: 3px;\n"
"            border-radius: 4px;\n"
"        }")
        self.config_label_2.setObjectName("config_label_2")
        self.horizontalLayout_21.addWidget(self.config_label_2)
        self.password = QtWidgets.QLineEdit(self.widget_26)
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setMinimumSize(QtCore.QSize(300, 35))
        self.password.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.password.setStyleSheet("QLineEdit {\n"
"            background-color: #f0f0f0;\n"
"            border: none;\n"
"            padding: 2px;\n"
"            border-radius: 4px;\n"
"            color: #333;\n"
"            font-size:13px\n"
"        }\n"
"\n"
"        QLineEdit:hover {\n"
"            background-color: #e0e0e0;\n"
"        }\n"
"\n"
"        QLineEdit:focus {\n"
"            background-color: #ffffff;\n"
"            border: 2px solid #007bff;\n"
"        }")
        self.password.setObjectName("password")
        self.horizontalLayout_21.addWidget(self.password)
        self.verticalLayout_2.addWidget(self.widget_26)
        self.verticalLayout_5.addWidget(self.widget_6)
        self.widget_8 = QtWidgets.QWidget(self.widget_4)
        self.widget_8.setMaximumSize(QtCore.QSize(200, 120))
        self.widget_8.setStyleSheet("QWidget {\n"
"          \n"
"            background-color:#92653c;\n"
"            color: #ffffff;\n"
"            padding: 8px;\n"
"            border-radius:20px;\n"
"        }")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_9 = QtWidgets.QWidget(self.widget_8)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.login = QtWidgets.QPushButton(self.widget_9, clicked=lambda : self.getLogin())
        self.login.setMinimumSize(QtCore.QSize(150, 35))
        self.login.setMaximumSize(QtCore.QSize(16777215, 35))
        self.login.setStyleSheet("QPushButton {\n"
"            background-color: #612d26;\n"
"            color: #ffffff;\n"
"            padding: 3px;\n"
"            border-radius: 12px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #3a211d;\n"
"        }\n"
"\n"
"        QPushButton:pressed {\n"
"            background-color: #8a605a;\n"
"        }")
        self.login.setObjectName("login")
        self.verticalLayout_3.addWidget(self.login)
        self.newuser = QtWidgets.QPushButton(self.widget_9, clicked=lambda :self.__createAccount())
        self.newuser.setMinimumSize(QtCore.QSize(100, 35))
        self.newuser.setMaximumSize(QtCore.QSize(16777215, 35))
        self.newuser.setStyleSheet("QPushButton {\n"
"            background-color: #612d26;\n"
"            color: #ffffff;\n"
"            padding: 3px;\n"
"            border-radius: 12px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #3a211d;\n"
"        }\n"
"\n"
"        QPushButton:pressed {\n"
"            background-color: #8a605a;\n"
"        }")
        self.newuser.setObjectName("newuser")
        self.verticalLayout_3.addWidget(self.newuser)
        self.horizontalLayout_4.addWidget(self.widget_9)
        self.verticalLayout_5.addWidget(self.widget_8, 0, QtCore.Qt.AlignHCenter)
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5.addWidget(self.widget_7)
        self.horizontalLayout_2.addWidget(self.widget_4, 0, QtCore.Qt.AlignHCenter)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_11 = QtWidgets.QWidget(self.widget_3)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.widget_11)
        self.pushButton.setStyleSheet("border:0px")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(180, 180))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_7.addWidget(self.widget_11)
        self.widget_10 = QtWidgets.QWidget(self.widget_3)
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.widget_10)
        self.label.setMaximumSize(QtCore.QSize(16777215, 300))
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticalLayout_7.addWidget(self.widget_10)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.broadcast = broadcast.Broadcast()

        self.movie2 = False
        self.start()
        self.bottonBar.setVisible(False)
        self.pLabel2.setVisible(False)
        self.isRunning = False

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'ADLaM Display\'; font-size:18pt; font-weight:600; color:#ffffff;\">ENTRAR/REGISTRAR</span></p></body></html>"))
        self.config_label.setText(_translate("Form", "CPF"))
        self.config_label_2.setText(_translate("Form", "SENHA"))
        self.login.setText(_translate("Form", "ENTRAR"))
        self.newuser.setText(_translate("Form", "REGISTRAR-SE"))
        self.label.setText(_translate("Form", '<html><head/><body><p align="center"><span style=" font-size:12pt; font-weight:600; color:#612d26;">TRABALHO BANCO DE DADOS I | CEFET-MG | 2023</span></p><p align="center"><span style=" font-size:12pt; font-weight:600; color:#612d26;"><br/>TARCÍSIO B. PRATES</span></p></body></html>'))




    def getLogin(self):

        user = self.user.text()
        password = self.password.text()

        if str(user).replace(" ", "") == "" or str(password).replace(" ", "") == "":
            self.msgBox("Informe o usuário e senha")
            return


        payload = [user, password]
        self.broadcast.bdData(payload)

        self.loginTh = bdQueryLogin.Login()
        self.loginTh.run(self.start, self.__loginDone, self.QLabelInfo)



    def __createAccount(self):

        try:

            self.page1 = QtWidgets.QWidget()
            self.newUserWidget = new_user.Ui_Form()
            self.newUserWidget.setupUi(self.page1)
            self.page1.setWindowModality(QtCore.Qt.ApplicationModal)
            self.page1.setWindowTitle("CRIAR NOVO USUÁRIO")
            icon = QIcon('./images/logo.png')
            self.page1.setWindowIcon(icon)

            self.page1.show()

        except:

            message = "Ocorreu um erro ao tentar gerar a janela " + traceback.format_exc()
            self.stackedWidget.setCurrentIndex(0)
            self.msgBox(message)



    def __loginDone(self):

        self.__end()

        if self.broadcast.credentials() != False:
            self.__userPage()


    def __userPage(self):


        try:
            self.page_2 = QtWidgets.QWidget()
            paPage = selector_page.Ui_Form(self.stackedWidget)
            paPage.setupUi(self.page_2)

            self.page_2.setObjectName("page_2")
            self.stackedWidget.insertWidget(2, self.page_2)
            self.stackedWidget.setCurrentIndex(2)

            if not self.stackedWidget.currentIndex() == 2:
                self.__userPage()
                time.sleep(1)

        except:

            message = "Ocorreu um erro ao tentar gerar a janela " + traceback.format_exc()
            self.stackedWidget.setCurrentIndex(0)
            self.msgBox(message)


    def msgBox(self, message, title="AVISO"):
        messageBox = QtWidgets.QMessageBox()
        messageBox.setWindowTitle(title)
        messageBox.setText(message)
        icon = QIcon('.\\ui\\../images/logo.png')
        messageBox.setWindowIcon(icon)
        messageBox.exec_()

    def start(self):

        self.isRunning = True

        if self.movie2 == False:

            self.movie2 = QMovie("./images/animation.gif")

            self.movie2.setScaledSize(QSize(60, 60))
            self.pLabel2 = QtWidgets.QLabel()
            self.pLabel2.setMovie(self.movie2)
            self.movie2.start()

            self.bottonBar = QtWidgets.QWidget()
            self.bottonBar.setStyleSheet("QWidget {background-color:#92653c;color: #ffffff;padding: 8px;border-radius:20px;}")
            self.bottonBar.setContentsMargins(20, 0, 0, 0)
            self.bottonLayout = QtWidgets.QHBoxLayout(self.bottonBar)
            self.bottonLayout.setContentsMargins(0, 0, 0, 0)

            self.bottonBar.setFixedHeight(60)

            self.bottonLayout.setAlignment(QtCore.Qt.AlignLeft)

            self.QLabelInfo = QtWidgets.QLabel()
            text = '<html><head/><body><p align="center"><span style=" font-size:12pt; font-weight:600; color:#ffffff;">Inicializando recursos</span></p></body></html>'
            self.QLabelInfo.setText(text)

            self.bottonLayout.addWidget(self.pLabel2)
            self.bottonLayout.setSpacing(9)
            self.bottonLayout.addWidget(self.QLabelInfo)

            self.verticalLayout_5.addWidget(self.bottonBar)
        else:
            self.bottonLayout.setAlignment(QtCore.Qt.AlignLeft)
            self.bottonBar.setVisible(True)
            self.pLabel2.setVisible(True)


    def __end(self):
        self.bottonLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.bottonBar.setVisible(True)
        self.pLabel2.setVisible(False)
        self.isRunning = False
        self.broadcast.labelinfo("")