# -*- coding: utf-8 -*-
import time
import traceback

# Form implementation generated from reading ui file '.\ui\selector_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

from pages import clientPage, shopPage
from utils import broadcast


class Ui_Form(object):

    def __init__(self, stackedWidget):
        self.stackedWidget = stackedWidget

    def setupUi(self, Form):
        self.Form = Form
        self.Form.setObjectName("Form")
        self.Form.resize(1207, 761)
        self.Form.setStyleSheet("background-color: rgb(255, 198, 0);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setMinimumSize(QtCore.QSize(50, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(52, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.backButton = QtWidgets.QPushButton(self.widget_5, clicked=lambda :self.backHome())
        self.backButton.setStyleSheet("\n"
"QPushButton{\n"
"border:0px;\n"
"border-radius: 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(213, 163, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(255, 239, 219);\n"
"}\n"
"")
        self.backButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon)
        self.backButton.setIconSize(QtCore.QSize(50, 50))
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_4.addWidget(self.backButton)
        self.horizontalLayout_2.addWidget(self.widget_5, 0, QtCore.Qt.AlignTop)
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setStyleSheet("background-color: #ffc600;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(50)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cliente = QtWidgets.QPushButton(self.widget_2, clicked=lambda : self.__openUserPage())
        self.cliente.setStyleSheet("\n"
"QPushButton{\n"
"border:0px;\n"
"border-radius: 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(213, 163, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(255, 239, 219);\n"
"}\n"
"")
        self.cliente.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\ui\\../images/client.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cliente.setIcon(icon1)
        self.cliente.setIconSize(QtCore.QSize(200, 200))
        self.cliente.setObjectName("cliente")
        self.verticalLayout.addWidget(self.cliente)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vendedor = QtWidgets.QPushButton(self.widget_3, clicked=lambda : self.__openShopPage())
        self.vendedor.setStyleSheet("\n"
"QPushButton{\n"
"border:0px;\n"
"border-radius: 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(213, 163, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(255, 239, 219);\n"
"}\n"
"")
        self.vendedor.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\ui\\../images/shop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vendedor.setIcon(icon2)
        self.vendedor.setIconSize(QtCore.QSize(200, 200))
        self.vendedor.setShortcut("")
        self.vendedor.setFlat(False)
        self.vendedor.setObjectName("vendedor")
        self.verticalLayout_2.addWidget(self.vendedor)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.horizontalLayout_2.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.widget_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.broadcast = broadcast.Broadcast()

        self.__setUserName()


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-family:\'ADLaM Display\'; font-size:18pt; font-weight:600; color:#ffffff;\">ÁREA DO CLIENTE</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-family:\'ADLaM Display\'; font-size:18pt; font-weight:600; color:#ffffff;\">ÁREA DO VENDEDOR</span></p></body></html>"))


    def __openUserPage(self):


        try:
            self.page_2 = QtWidgets.QWidget()
            paPage = clientPage.Ui_Form(self.stackedWidget)
            paPage.setupUi(self.page_2)

            self.page_2.setObjectName("page_2")
            self.stackedWidget.insertWidget(3, self.page_2)
            self.stackedWidget.setCurrentIndex(3)

            if not self.stackedWidget.currentIndex() == 3:
                self.__openUserPage()
                time.sleep(1)

        except:

            message = "Ocorreu um erro ao tentar gerar a janela " + traceback.format_exc()
            self.stackedWidget.setCurrentIndex(0)
            self.msgBox(message)


    def __openShopPage(self):

        try:
            self.page_4 = QtWidgets.QWidget()
            paPage = shopPage.Ui_Form(self.stackedWidget)
            paPage.setupUi(self.page_4)

            self.page_4.setObjectName("page_4")
            self.stackedWidget.insertWidget(4, self.page_4)
            self.stackedWidget.setCurrentIndex(4)

            if not self.stackedWidget.currentIndex() == 4:
                self.__openShopPage()
                time.sleep(1)
            else:
                paPage.showServices()

        except:

            message = "Ocorreu um erro ao tentar gerar a janela " + traceback.format_exc()
            self.stackedWidget.setCurrentIndex(0)
            self.msgBox(message)



    def msgBox(self, message, title="AVISO"):
        messageBox = QtWidgets.QMessageBox()
        messageBox.setWindowTitle(title)
        messageBox.setText(message)
        icon = QIcon('.\\ui\\../images/logo.png')
        messageBox.setWindowIcon(icon)
        messageBox.exec_()

    def backHome(self):

        self.broadcast.credentials("")
        self.stackedWidget.setCurrentIndex(0)



    def __setUserName(self):

        text = '<html><head/><body><p><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">SEJA BEM-VINDO,</span></p><p><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">#USER_NAME!</span></p><p><span style=\" font-size:36pt;\"><br/></span></p><p><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">ESCOLHA QUAL ÁREA</span></p><p><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">DESEJA ACESSAR.</span></p><p><span style=\" font-size:36pt;\"><br/></span></p></body></html>'

        name = str(self.broadcast.credentials()["NAME"])


        self.label_3.setText(text.replace('#USER_NAME', name.upper()))
