# -*- coding: utf-8 -*-
import time
import traceback

# Form implementation generated from reading ui file '.\ui\userPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

from subPages import shopServicePage, shopInfoPage


class Ui_Form(object):

    def __init__(self, stackedWidget):
        self.stackedWidget = stackedWidget
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1208, 762)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("background-color: #ffc600;")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_2.setStyleSheet("QWidget {\n"
"          \n"
"            background-color:rgb(255, 226, 127);\n"
"            color: #ffffff;\n"
"            padding: 8px;\n"
"            border-radius:20px;\n"
"        }")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.findServices = QtWidgets.QPushButton(self.widget_4, clicked=lambda: self.showServices())
        self.findServices.setStyleSheet("\n"
"QPushButton{\n"
"border:0px;\n"
"border-radius: 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(213, 163, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(255, 239, 219);\n"
"}\n"
"")
        self.findServices.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../images/worker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findServices.setIcon(icon)
        self.findServices.setIconSize(QtCore.QSize(120, 120))
        self.findServices.setObjectName("findServices")
        self.verticalLayout_4.addWidget(self.findServices)
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.myServices = QtWidgets.QPushButton(self.widget_5)
        self.myServices.setStyleSheet("\n"
"QPushButton{\n"
"border:0px;\n"
"border-radius: 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(213, 163, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(255, 239, 219);\n"
"}\n"
"")
        self.myServices.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\ui\\../images/solicitations.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.myServices.setIcon(icon1)
        self.myServices.setIconSize(QtCore.QSize(120, 120))
        self.myServices.setObjectName("myServices")
        self.verticalLayout_5.addWidget(self.myServices)
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.profile = QtWidgets.QPushButton(self.widget_7, clicked=lambda : self.showInfo())
        self.profile.setStyleSheet("\n"
"QPushButton{\n"
"border:0px;\n"
"border-radius: 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(213, 163, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: rgb(255, 239, 219);\n"
"}\n"
"")
        self.profile.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\ui\\../images/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile.setIcon(icon2)
        self.profile.setIconSize(QtCore.QSize(120, 120))
        self.profile.setObjectName("profile")
        self.verticalLayout_6.addWidget(self.profile)
        self.label_3 = QtWidgets.QLabel(self.widget_7)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.verticalLayout_3.addWidget(self.widget_7)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget_client = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget_client.setObjectName("stackedWidget_client")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_client.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_client.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget_client)
        self.horizontalLayout.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">SERVIÇOS</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">SOLICITAÇOES</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">PERFIL</span></p></body></html>"))




    def showServices(self):

        try:
            self.page_2 = QtWidgets.QWidget()
            paPage = shopServicePage.Ui_Form()
            paPage.setupUi(self.page_2)

            self.page_2.setObjectName("page_2")
            self.stackedWidget_client.insertWidget(0, self.page_2)
            self.stackedWidget_client.setCurrentIndex(0)

        except:

            message = "Ocorreu um erro ao tentar gerar a janela " + traceback.format_exc()
            self.stackedWidget.setCurrentIndex(0)
            self.msgBox(message)


    def showInfo(self):

        try:
            self.page_2 = QtWidgets.QWidget()
            paPage = shopInfoPage.Ui_Form(self.stackedWidget)
            paPage.setupUi(self.page_2)

            self.page_2.setObjectName("page_2")
            self.stackedWidget_client.insertWidget(2, self.page_2)
            self.stackedWidget_client.setCurrentIndex(2)

        except:

            message = "Ocorreu um erro ao tentar gerar a janela " + traceback.format_exc()
            self.stackedWidget.setCurrentIndex(0)
            self.msgBox(message)


    def msgBox(self, message, title="AVISO"):
        messageBox = QtWidgets.QMessageBox()
        messageBox.setWindowTitle(title)
        messageBox.setText(message)
        icon = QIcon('.\\ui\\../images/logo.png')
        messageBox.setWindowIcon(icon)
        messageBox.exec_()