# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\clientServicePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QDialog, QCalendarWidget

from services import connection_db
from utils import broadcast


class Ui_Form(object):
        def setupUi(self, Form):
                Form.setObjectName("Form")
                Form.resize(975, 726)
                Form.setStyleSheet("background-color: #ffc600;")
                self.verticalLayout = QtWidgets.QVBoxLayout(Form)
                self.verticalLayout.setObjectName("verticalLayout")
                self.widget_2 = QtWidgets.QWidget(Form)
                self.widget_2.setMaximumSize(QtCore.QSize(16777215, 200))
                self.widget_2.setStyleSheet("QWidget {\n"
                "          \n"
                "            background-color:rgb(255, 226, 127);\n"
                "            color: #ffffff;\n"
                "            padding: 8px;\n"
                "            border-radius:20px;\n"
                "        }")
                self.widget_2.setObjectName("widget_2")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
                self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.widget_3 = QtWidgets.QWidget(self.widget_2)
                self.widget_3.setObjectName("widget_3")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.label = QtWidgets.QLabel(self.widget_3)
                self.label.setObjectName("label")
                self.verticalLayout_2.addWidget(self.label)
                self.widget_26 = QtWidgets.QWidget(self.widget_3)
                self.widget_26.setMinimumSize(QtCore.QSize(0, 40))
                self.widget_26.setMaximumSize(QtCore.QSize(16777215, 40))
                self.widget_26.setObjectName("widget_26")
                self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_26)
                self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_3.setSpacing(3)
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")
                self.config_label_2 = QtWidgets.QLabel(self.widget_26)
                self.config_label_2.setMinimumSize(QtCore.QSize(120, 35))
                self.config_label_2.setMaximumSize(QtCore.QSize(100, 16777215))
                self.config_label_2.setStyleSheet("QLabel {\n"
                "            background-color:#612d26;\n"
                "            font-weight: bold;\n"
                "            color: rgb(255, 255, 255);\n"
                "            padding: 3px;\n"
                "            border-radius: 4px;\n"
                "        }")
                self.config_label_2.setObjectName("config_label_2")
                self.horizontalLayout_3.addWidget(self.config_label_2)
                self.serviceName = QtWidgets.QLineEdit(self.widget_26)
                self.serviceName.setMinimumSize(QtCore.QSize(300, 35))
                self.serviceName.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.serviceName.setStyleSheet("QLineEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }\n"
                "\n"
                "        QLineEdit:hover {\n"
                "            background-color: #e0e0e0;\n"
                "        }\n"
                "\n"
                "        QLineEdit:focus {\n"
                "            background-color: #ffffff;\n"
                "            border: 2px solid #007bff;\n"
                "        }")
                self.serviceName.setObjectName("serviceName")
                self.horizontalLayout_3.addWidget(self.serviceName)
                self.verticalLayout_2.addWidget(self.widget_26)
                self.widget_27 = QtWidgets.QWidget(self.widget_3)
                self.widget_27.setMinimumSize(QtCore.QSize(0, 40))
                self.widget_27.setMaximumSize(QtCore.QSize(16777215, 40))
                self.widget_27.setObjectName("widget_27")
                self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_27)
                self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_5.setSpacing(3)
                self.horizontalLayout_5.setObjectName("horizontalLayout_5")
                self.config_label_3 = QtWidgets.QLabel(self.widget_27)
                self.config_label_3.setMinimumSize(QtCore.QSize(120, 35))
                self.config_label_3.setMaximumSize(QtCore.QSize(100, 16777215))
                self.config_label_3.setStyleSheet("QLabel {\n"
                "            background-color:#612d26;\n"
                "            font-weight: bold;\n"
                "            color: rgb(255, 255, 255);\n"
                "            padding: 3px;\n"
                "            border-radius: 4px;\n"
                "        }")
                self.config_label_3.setObjectName("config_label_3")
                self.horizontalLayout_5.addWidget(self.config_label_3)
                self.shopName = QtWidgets.QLineEdit(self.widget_27)
                self.shopName.setMinimumSize(QtCore.QSize(300, 35))
                self.shopName.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.shopName.setStyleSheet("QLineEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }\n"
                "\n"
                "        QLineEdit:hover {\n"
                "            background-color: #e0e0e0;\n"
                "        }\n"
                "\n"
                "        QLineEdit:focus {\n"
                "            background-color: #ffffff;\n"
                "            border: 2px solid #007bff;\n"
                "        }")
                self.shopName.setObjectName("shopName")
                self.horizontalLayout_5.addWidget(self.shopName)
                self.verticalLayout_2.addWidget(self.widget_27)
                self.horizontalLayout.addWidget(self.widget_3)
                self.widget_4 = QtWidgets.QWidget(self.widget_2)
                self.widget_4.setObjectName("widget_4")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.widget_8 = QtWidgets.QWidget(self.widget_4)
                self.widget_8.setMaximumSize(QtCore.QSize(200, 120))
                self.widget_8.setStyleSheet("QWidget {\n"
                "          \n"
                "            background-color:#92653c;\n"
                "            color: #ffffff;\n"
                "            padding: 8px;\n"
                "            border-radius:20px;\n"
                "        }")
                self.widget_8.setObjectName("widget_8")
                self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
                self.horizontalLayout_4.setObjectName("horizontalLayout_4")
                self.widget_9 = QtWidgets.QWidget(self.widget_8)
                self.widget_9.setObjectName("widget_9")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_9)
                self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.buscar = QtWidgets.QPushButton(self.widget_9, clicked=lambda : self.__search())
                self.buscar.setMinimumSize(QtCore.QSize(150, 35))
                self.buscar.setMaximumSize(QtCore.QSize(16777215, 35))
                self.buscar.setStyleSheet("QPushButton {\n"
                "            background-color: #612d26;\n"
                "            color: #ffffff;\n"
                "            padding: 3px;\n"
                "            border-radius: 12px;\n"
                "        }\n"
                "\n"
                "        QPushButton:hover {\n"
                "            background-color: #3a211d;\n"
                "        }\n"
                "\n"
                "        QPushButton:pressed {\n"
                "            background-color: #8a605a;\n"
                "        }")
                self.buscar.setObjectName("buscar")
                self.verticalLayout_3.addWidget(self.buscar)
                self.horizontalLayout_4.addWidget(self.widget_9)
                self.horizontalLayout_2.addWidget(self.widget_8)
                self.horizontalLayout.addWidget(self.widget_4)
                self.verticalLayout.addWidget(self.widget_2)
                self.widget = QtWidgets.QWidget(Form)
                self.widget.setObjectName("widget")
                self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
                self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_6.setSpacing(9)
                self.horizontalLayout_6.setObjectName("horizontalLayout_6")
                self.widget_5 = QtWidgets.QWidget(self.widget)
                self.widget_5.setMinimumSize(QtCore.QSize(500, 0))
                self.widget_5.setObjectName("widget_5")
                self.horizontalLayout_6.addWidget(self.widget_5)
                self.frame = QtWidgets.QFrame(self.widget)
                self.frame.setStyleSheet("QWidget {\n"
                "          \n"
                "            background-color:rgb(255, 226, 127);\n"
                "            color: #ffffff;\n"
                "            padding: 8px;\n"
                "            border-radius:20px;\n"
                "        }")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
                self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_4.setObjectName("verticalLayout_4")
                self.widget_7 = QtWidgets.QWidget(self.frame)
                self.widget_7.setMinimumSize(QtCore.QSize(50, 0))
                self.widget_7.setMaximumSize(QtCore.QSize(16777215, 50))
                self.widget_7.setObjectName("widget_7")
                self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_7)
                self.verticalLayout_5.setContentsMargins(0, 0, 0, -1)
                self.verticalLayout_5.setObjectName("verticalLayout_5")
                self.label_2 = QtWidgets.QLabel(self.widget_7)
                self.label_2.setObjectName("label_2")
                self.verticalLayout_5.addWidget(self.label_2)
                self.verticalLayout_4.addWidget(self.widget_7)
                self.widget_6 = QtWidgets.QWidget(self.frame)
                self.widget_6.setObjectName("widget_6")
                self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_6)
                self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_6.setSpacing(9)
                self.verticalLayout_6.setObjectName("verticalLayout_6")
                self.widget_31 = QtWidgets.QWidget(self.widget_6)
                self.widget_31.setMinimumSize(QtCore.QSize(0, 40))
                self.widget_31.setMaximumSize(QtCore.QSize(16777215, 40))
                self.widget_31.setObjectName("widget_31")
                self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_31)
                self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_13.setSpacing(3)
                self.horizontalLayout_13.setObjectName("horizontalLayout_13")
                self.config_label_10 = QtWidgets.QLabel(self.widget_31)
                self.config_label_10.setMinimumSize(QtCore.QSize(120, 35))
                self.config_label_10.setMaximumSize(QtCore.QSize(100, 16777215))
                self.config_label_10.setStyleSheet("QLabel {\n"
                "            background-color:#612d26;\n"
                "            font-weight: bold;\n"
                "            color: rgb(255, 255, 255);\n"
                "            padding: 3px;\n"
                "            border-radius: 4px;\n"
                "        }")
                self.config_label_10.setObjectName("config_label_10")
                self.horizontalLayout_13.addWidget(self.config_label_10)
                self.inShopName = QtWidgets.QLineEdit(self.widget_31)
                self.inShopName.setMinimumSize(QtCore.QSize(300, 35))
                self.inShopName.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.inShopName.setStyleSheet("QLineEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }\n"
                "\n"
                "        QLineEdit:hover {\n"
                "            background-color: #e0e0e0;\n"
                "        }\n"
                "\n"
                "        QLineEdit:focus {\n"
                "            background-color: #ffffff;\n"
                "            border: 2px solid #007bff;\n"
                "        }")
                self.inShopName.setObjectName("inShopName")
                self.horizontalLayout_13.addWidget(self.inShopName)
                self.verticalLayout_6.addWidget(self.widget_31)
                self.widget_30 = QtWidgets.QWidget(self.widget_6)
                self.widget_30.setMinimumSize(QtCore.QSize(0, 40))
                self.widget_30.setMaximumSize(QtCore.QSize(16777215, 40))
                self.widget_30.setObjectName("widget_30")
                self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_30)
                self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_12.setSpacing(3)
                self.horizontalLayout_12.setObjectName("horizontalLayout_12")
                self.config_label_9 = QtWidgets.QLabel(self.widget_30)
                self.config_label_9.setMinimumSize(QtCore.QSize(120, 35))
                self.config_label_9.setMaximumSize(QtCore.QSize(100, 16777215))
                self.config_label_9.setStyleSheet("QLabel {\n"
                "            background-color:#612d26;\n"
                "            font-weight: bold;\n"
                "            color: rgb(255, 255, 255);\n"
                "            padding: 3px;\n"
                "            border-radius: 4px;\n"
                "        }")
                self.config_label_9.setObjectName("config_label_9")
                self.horizontalLayout_12.addWidget(self.config_label_9)
                self.inClientName = QtWidgets.QLineEdit(self.widget_30)
                self.inClientName.setMinimumSize(QtCore.QSize(300, 35))
                self.inClientName.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.inClientName.setStyleSheet("QLineEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }\n"
                "\n"
                "        QLineEdit:hover {\n"
                "            background-color: #e0e0e0;\n"
                "        }\n"
                "\n"
                "        QLineEdit:focus {\n"
                "            background-color: #ffffff;\n"
                "            border: 2px solid #007bff;\n"
                "        }")
                self.inClientName.setObjectName("inClientName")
                self.horizontalLayout_12.addWidget(self.inClientName)
                self.verticalLayout_6.addWidget(self.widget_30)
                self.widget_29 = QtWidgets.QWidget(self.widget_6)
                self.widget_29.setMinimumSize(QtCore.QSize(0, 40))
                self.widget_29.setMaximumSize(QtCore.QSize(16777215, 40))
                self.widget_29.setObjectName("widget_29")
                self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_29)
                self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_11.setSpacing(3)
                self.horizontalLayout_11.setObjectName("horizontalLayout_11")
                self.config_label_8 = QtWidgets.QLabel(self.widget_29)
                self.config_label_8.setMinimumSize(QtCore.QSize(120, 35))
                self.config_label_8.setMaximumSize(QtCore.QSize(100, 16777215))
                self.config_label_8.setStyleSheet("QLabel {\n"
                "            background-color:#612d26;\n"
                "            font-weight: bold;\n"
                "            color: rgb(255, 255, 255);\n"
                "            padding: 3px;\n"
                "            border-radius: 4px;\n"
                "        }")
                self.config_label_8.setObjectName("config_label_8")
                self.horizontalLayout_11.addWidget(self.config_label_8)
                self.inServiceName = QtWidgets.QLineEdit(self.widget_29)
                self.inServiceName.setMinimumSize(QtCore.QSize(300, 35))
                self.inServiceName.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.inServiceName.setStyleSheet("QLineEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }\n"
                "\n"
                "        QLineEdit:hover {\n"
                "            background-color: #e0e0e0;\n"
                "        }\n"
                "\n"
                "        QLineEdit:focus {\n"
                "            background-color: #ffffff;\n"
                "            border: 2px solid #007bff;\n"
                "        }")
                self.inServiceName.setObjectName("inServiceName")
                self.horizontalLayout_11.addWidget(self.inServiceName)
                self.verticalLayout_6.addWidget(self.widget_29)
                self.widget_28 = QtWidgets.QWidget(self.widget_6)
                self.widget_28.setMinimumSize(QtCore.QSize(0, 40))
                self.widget_28.setMaximumSize(QtCore.QSize(16777215, 40))
                self.widget_28.setObjectName("widget_28")
                self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_28)
                self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_10.setSpacing(3)
                self.horizontalLayout_10.setObjectName("horizontalLayout_10")
                self.config_label_7 = QtWidgets.QLabel(self.widget_28)
                self.config_label_7.setMinimumSize(QtCore.QSize(120, 35))
                self.config_label_7.setMaximumSize(QtCore.QSize(100, 16777215))
                self.config_label_7.setStyleSheet("QLabel {\n"
                "            background-color:#612d26;\n"
                "            font-weight: bold;\n"
                "            color: rgb(255, 255, 255);\n"
                "            padding: 3px;\n"
                "            border-radius: 4px;\n"
                "        }")
                self.config_label_7.setObjectName("config_label_7")
                self.horizontalLayout_10.addWidget(self.config_label_7)
                self.dataServiceName = QtWidgets.QLineEdit(self.widget_28)
                self.dataServiceName.mousePressEvent = self.showCalendarDialog
                self.dataServiceName.setMinimumSize(QtCore.QSize(200, 35))
                self.dataServiceName.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.dataServiceName.setStyleSheet("QLineEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }\n"
                "\n"
                "        QLineEdit:hover {\n"
                "            background-color: #e0e0e0;\n"
                "        }\n"
                "\n"
                "        QLineEdit:focus {\n"
                "            background-color: #ffffff;\n"
                "            border: 2px solid #007bff;\n"
                "        }")
                self.dataServiceName.setObjectName("dataServiceName")

                self.idServiceName = QtWidgets.QLineEdit(self.widget_28)
                self.idServiceName.setMinimumSize(QtCore.QSize(50, 35))
                self.idServiceName.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.idServiceName.setStyleSheet("QLineEdit {\n"
                                                   "            background-color: #f0f0f0;\n"
                                                   "            border: none;\n"
                                                   "            padding: 2px;\n"
                                                   "            border-radius: 4px;\n"
                                                   "            color: #333;\n"
                                                   "            font-size:13px\n"
                                                   "        }\n"
                                                   "\n"
                                                   "        QLineEdit:hover {\n"
                                                   "            background-color: #e0e0e0;\n"
                                                   "        }\n"
                                                   "\n"
                                                   "        QLineEdit:focus {\n"
                                                   "            background-color: #ffffff;\n"
                                                   "            border: 2px solid #007bff;\n"
                                                   "        }")

                self.idShop = QtWidgets.QLineEdit(self.widget_28)
                self.idShop.setMinimumSize(QtCore.QSize(50, 35))
                self.idShop.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.idShop.setStyleSheet("QLineEdit {\n"
                                                   "            background-color: #f0f0f0;\n"
                                                   "            border: none;\n"
                                                   "            padding: 2px;\n"
                                                   "            border-radius: 4px;\n"
                                                   "            color: #333;\n"
                                                   "            font-size:13px\n"
                                                   "        }\n"
                                                   "\n"
                                                   "        QLineEdit:hover {\n"
                                                   "            background-color: #e0e0e0;\n"
                                                   "        }\n"
                                                   "\n"
                                                   "        QLineEdit:focus {\n"
                                                   "            background-color: #ffffff;\n"
                                                   "            border: 2px solid #007bff;\n"
                                                   "        }")





                self.horizontalLayout_10.addWidget(self.dataServiceName)
                self.horizontalLayout_10.addWidget(self.idServiceName)
                self.horizontalLayout_10.addWidget(self.idShop)

                self.verticalLayout_6.addWidget(self.widget_28)
                self.inObs = QtWidgets.QTextEdit(self.widget_6)
                self.inObs.setObjectName("inObs")
                self.inObs.setStyleSheet('''QTextEdit {
                    background-color: #f0f0f0;
                    border: none;
                    padding: 2px;
                    border-radius: 4px;
                    color: #333;
                    font-size:13px
                }''')
                self.verticalLayout_6.addWidget(self.inObs)
                self.widget_10 = QtWidgets.QWidget(self.widget_6)
                self.widget_10.setMinimumSize(QtCore.QSize(0, 50))
                self.widget_10.setMaximumSize(QtCore.QSize(16777215, 80))
                self.widget_10.setStyleSheet("QWidget {\n"
                "          \n"
                "            background-color:#92653c;\n"
                "            color: #ffffff;\n"
                "            padding: 8px;\n"
                "            border-radius:20px;\n"
                "        }")
                self.widget_10.setObjectName("widget_10")
                self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_10)
                self.horizontalLayout_14.setObjectName("horizontalLayout_14")
                self.inContratar = QtWidgets.QPushButton(self.widget_10, clicked=lambda :self.queueService())
                self.inContratar.setMinimumSize(QtCore.QSize(150, 35))
                self.inContratar.setMaximumSize(QtCore.QSize(16777215, 35))
                self.inContratar.setStyleSheet("QPushButton {\n"
                "            background-color: #612d26;\n"
                "            color: #ffffff;\n"
                "            padding: 3px;\n"
                "            border-radius: 12px;\n"
                "        }\n"
                "\n"
                "        QPushButton:hover {\n"
                "            background-color: #3a211d;\n"
                "        }\n"
                "\n"
                "        QPushButton:pressed {\n"
                "            background-color: #8a605a;\n"
                "        }")
                self.inContratar.setObjectName("inContratar")
                self.horizontalLayout_14.addWidget(self.inContratar)
                self.inSave = QtWidgets.QPushButton(self.widget_10)
                self.inSave.setMinimumSize(QtCore.QSize(150, 35))
                self.inSave.setMaximumSize(QtCore.QSize(16777215, 35))
                self.inSave.setStyleSheet("QPushButton {\n"
                "            background-color: #612d26;\n"
                "            color: #ffffff;\n"
                "            padding: 3px;\n"
                "            border-radius: 12px;\n"
                "        }\n"
                "\n"
                "        QPushButton:hover {\n"
                "            background-color: #3a211d;\n"
                "        }\n"
                "\n"
                "        QPushButton:pressed {\n"
                "            background-color: #8a605a;\n"
                "        }")
                self.inSave.setObjectName("inSave")
                self.horizontalLayout_14.addWidget(self.inSave)
                self.verticalLayout_6.addWidget(self.widget_10)
                self.verticalLayout_4.addWidget(self.widget_6)
                self.horizontalLayout_6.addWidget(self.frame)
                self.verticalLayout.addWidget(self.widget)

                self.retranslateUi(Form)
                QtCore.QMetaObject.connectSlotsByName(Form)

                self.broadcast = broadcast.Broadcast()
                self.oracleBD = connection_db.Oracle_db()

                self.dyLayout = QtWidgets.QVBoxLayout(self.widget_5)
                self.dyLayout.setContentsMargins(0, 0, 0, 0)

                self.dynamicWindowApps = QtWidgets.QScrollArea()
                self.dyLayout.addWidget(self.dynamicWindowApps)

                self.payload = False

                self.__showAll()


                self.inShopName.setReadOnly(True)
                self.inClientName.setReadOnly(True)
                self.idServiceName.setReadOnly(True)
                self.idServiceName.setReadOnly(True)
                self.idShop.setReadOnly(True)



        def retranslateUi(self, Form):
                _translate = QtCore.QCoreApplication.translate
                Form.setWindowTitle(_translate("Form", "Form"))
                self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">PROCURAR POR SERVIÇOS</span></p></body></html>"))
                self.config_label_2.setText(_translate("Form", "SERVIÇO"))
                self.config_label_3.setText(_translate("Form", "PRESTADOR"))
                self.buscar.setText(_translate("Form", "BUSCAR"))
                self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">NOTA DE SERVIÇO</span></p></body></html>"))
                self.config_label_10.setText(_translate("Form", "PRESTADOR"))
                self.config_label_9.setText(_translate("Form", "CONTRATANTE"))
                self.config_label_8.setText(_translate("Form", "SERVIÇO"))
                self.config_label_7.setText(_translate("Form", "DATA"))
                self.inContratar.setText(_translate("Form", "CONTRATAR"))
                self.inSave.setText(_translate("Form", "SALVAR"))


        def __showAll(self):

                self.oracleBD.shopListAllService()

                response = self.broadcast.dataTransfer()

                if response == False:

                        print("Default page")

                else:
                        self.__showResults(response)


        def __search(self):

                serviceName = self.serviceName.text()
                forName = self.shopName.text()

                payload = [serviceName, forName]


                if str(serviceName).replace(" ","") == "" and str(forName).replace(" ", "") == "":
                        self.__showAll()
                        return


                self.broadcast.bdData(payload)
                self.oracleBD.clientListService()


                response = self.broadcast.dataTransfer()

                if response == False:

                        print("Default page")

                else:
                        self.__showResults(response)

        def __showResults(self, response):

                self.wQWidget = QtWidgets.QWidget()
                self.wQLayout = QtWidgets.QVBoxLayout(self.wQWidget)
                self.wQLayout.setAlignment(Qt.AlignTop)



                for item in response:
                        itemWidget = QtWidgets.QWidget()
                        itemWidget.setStyleSheet(self.__getWidgetStyle())
                        itemWidget.setFixedHeight(50)
                        itemLayout = QtWidgets.QHBoxLayout(itemWidget)
                        itemWidget.setContentsMargins(0, 0, 0, 0)

                        idText = QtWidgets.QLineEdit()
                        idText.setFixedHeight(30)
                        idText.setFixedWidth(30)
                        idText.setText(str(item[0]))
                        idText.setDisabled(True)
                        idText.setStyleSheet(self.__getLineStyle())

                        serviceText = QtWidgets.QLineEdit()
                        serviceText.setFixedHeight(30)

                        if len(item[2]) >= 30:
                                content = str(item[2])[:30] + "..."
                        else:
                                content = item[2]

                        serviceText.setText(content)
                        serviceText.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
                        serviceText.setReadOnly(True)
                        serviceText.setStyleSheet(self.__getLineStyle())

                        priceText = QtWidgets.QLineEdit()
                        priceText.setFixedHeight(30)
                        priceText.setFixedWidth(80)
                        priceText.setText("R$: " + str(item[4]))
                        priceText.setDisabled(True)
                        priceText.setStyleSheet(self.__getLineStyle())

                        editButton = QtWidgets.QPushButton()
                        editButton.setFixedHeight(30)
                        editButton.setText('➡️')
                        editButton.setStyleSheet(self.__getButtonStyle())
                        editButton.clicked.connect(lambda state, payload=item: self.__insertData(payload))

                        itemLayout.addWidget(idText)
                        itemLayout.addWidget(serviceText)
                        itemLayout.addWidget(priceText)
                        itemLayout.addWidget(editButton)

                        self.wQLayout.addWidget(itemWidget)

                self.dynamicWindowApps.setStyleSheet("border:0px")
                # self.dynamicWindowApps.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                # dynamicWindowApps.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.dynamicWindowApps.setWidgetResizable(True)
                self.dynamicWindowApps.setWidget(self.wQWidget)



        def __insertData(self, payload):

                self.payload = payload

                query = [payload[0]]
                self.broadcast.bdData(query)
                self.oracleBD.getShopInfoByIdService()

                response = self.broadcast.dataTransfer()

                self.inShopName.setText(response[2])
                self.inClientName.setText(self.broadcast.credentials()["NAME"])
                self.idServiceName.setText(str(payload[0]))
                self.idShop.setText(str(response[0]))
                self.inServiceName.setText(payload[2])



        def showCalendarDialog(self, event):
                # Create a QDialog to show the calendar
                dialog = QDialog(self.widget)
                dialog.setWindowTitle('SELECIONE A DATA PARA O SERVIÇO')

                # Calendar Widget
                calendar = QCalendarWidget(dialog)
                calendar.clicked.connect(lambda: self.showDate(calendar.selectedDate(), dialog))
                dialog.layout = QtWidgets.QVBoxLayout(dialog)
                dialog.layout.addWidget(calendar)

                dialog.exec_()

        def showDate(self, date, dialog):


                selected_date = date.toString("dd-MM-yyyy")
                self.dataServiceName.setText(str(selected_date))

                dialog.accept()


        def queueService(self):

                id_servico = self.idServiceName.text()
                data_servico = self.dataServiceName.text()
                nome_servico = self.inServiceName.text()
                valor = str(self.payload[4])
                observacao = self.inObs.toPlainText()
                cpf_cliente = self.broadcast.credentials()["CPF"]

                payload = [id_servico, cpf_cliente, nome_servico, valor, data_servico, observacao]

                self.broadcast.bdData(payload)
                self.oracleBD.queueService()

        def __getLineStyle(self):

                return '''QLineEdit {
            background-color: #f0f0f0;
            border: none;
            padding: 2px;
            border-radius: 4px;
            color: #333;
			font-size:13px
        }

        QLineEdit:hover {
            background-color: #e0e0e0;
        }

        QLineEdit:focus {
            background-color: #ffffff;
            border: 2px solid #007bff;
        }'''

        def __getButtonStyle(self):

                return '''QPushButton {
                            background-color: #612d26;
                            color: #ffffff;
                            padding: 3px;
                            border-radius: 12px;
                        }

                        QPushButton:hover {
                            background-color: #3a211d;
                        }

                        QPushButton:pressed {
                            background-color: #8a605a;
                        }'''

        def __getWidgetStyle(self):

                return '''QWidget {

			background-color:rgb(255, 226, 127);
            color: #ffffff;
            padding: 8px;
            border-radius:20px;
        }'''