# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\shopInfoPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from services import connection_db
from utils import broadcast


class Ui_Form(object):

        def __init__(self, stackedWidget):
                self.stackedWidget = stackedWidget

        def setupUi(self, Form):
                Form.setObjectName("Form")
                Form.resize(975, 726)
                Form.setStyleSheet("background-color: #ffc600;")
                self.verticalLayout = QtWidgets.QVBoxLayout(Form)
                self.verticalLayout.setObjectName("verticalLayout")
                self.widget_2 = QtWidgets.QWidget(Form)
                self.widget_2.setMaximumSize(QtCore.QSize(16777215, 200))
                self.widget_2.setStyleSheet("QWidget {\n"
                "          \n"
                "            background-color:rgb(255, 226, 127);\n"
                "            color: #ffffff;\n"
                "            padding: 8px;\n"
                "            border-radius:20px;\n"
                "        }")
                self.widget_2.setObjectName("widget_2")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
                self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.verticalLayout.addWidget(self.widget_2)
                self.widget = QtWidgets.QWidget(Form)
                self.widget.setObjectName("widget")
                self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
                self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_6.setSpacing(9)
                self.horizontalLayout_6.setObjectName("horizontalLayout_6")
                self.widget_5 = QtWidgets.QWidget(self.widget)
                self.widget_5.setMinimumSize(QtCore.QSize(500, 0))
                self.widget_5.setObjectName("widget_5")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
                self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_2.setSpacing(0)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.frame_2 = QtWidgets.QFrame(self.widget_5)
                self.frame_2.setStyleSheet("QWidget {\n"
                "          \n"
                "            background-color:rgb(255, 226, 127);\n"
                "            color: #ffffff;\n"
                "            padding: 8px;\n"
                "            border-radius:20px;\n"
                "        }")
                self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_2.setObjectName("frame_2")
                self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
                self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_7.setObjectName("verticalLayout_7")
                self.widget_8 = QtWidgets.QWidget(self.frame_2)
                self.widget_8.setMinimumSize(QtCore.QSize(50, 0))
                self.widget_8.setMaximumSize(QtCore.QSize(16777215, 50))
                self.widget_8.setObjectName("widget_8")
                self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_8)
                self.verticalLayout_8.setContentsMargins(0, 0, 0, -1)
                self.verticalLayout_8.setObjectName("verticalLayout_8")
                self.label_3 = QtWidgets.QLabel(self.widget_8)
                self.label_3.setObjectName("label_3")
                self.verticalLayout_8.addWidget(self.label_3)
                self.verticalLayout_7.addWidget(self.widget_8)
                self.widget_3 = QtWidgets.QWidget(self.frame_2)
                self.widget_3.setMinimumSize(QtCore.QSize(0, 200))
                self.widget_3.setSizeIncrement(QtCore.QSize(0, 0))
                self.widget_3.setObjectName("widget_3")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.pushButton = QtWidgets.QPushButton(self.widget_3)
                self.pushButton.setText("")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(".\\ui\\../images/guest.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.pushButton.setIcon(icon)
                self.pushButton.setIconSize(QtCore.QSize(150, 150))
                self.pushButton.setObjectName("pushButton")
                self.verticalLayout_2.addWidget(self.pushButton)
                self.verticalLayout_7.addWidget(self.widget_3)
                self.widget_9 = QtWidgets.QWidget(self.frame_2)
                self.widget_9.setObjectName("widget_9")
                self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_9)
                self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_9.setSpacing(9)
                self.verticalLayout_9.setObjectName("verticalLayout_9")
                self.widget_32 = QtWidgets.QWidget(self.widget_9)
                self.widget_32.setMinimumSize(QtCore.QSize(0, 40))
                self.widget_32.setMaximumSize(QtCore.QSize(16777215, 40))
                self.widget_32.setObjectName("widget_32")
                self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_32)
                self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_15.setSpacing(3)
                self.horizontalLayout_15.setObjectName("horizontalLayout_15")
                self.config_label_11 = QtWidgets.QLabel(self.widget_32)
                self.config_label_11.setMinimumSize(QtCore.QSize(120, 35))
                self.config_label_11.setMaximumSize(QtCore.QSize(100, 16777215))
                self.config_label_11.setStyleSheet("QLabel {\n"
                "            background-color:#612d26;\n"
                "            font-weight: bold;\n"
                "            color: rgb(255, 255, 255);\n"
                "            padding: 3px;\n"
                "            border-radius: 4px;\n"
                "        }")
                self.config_label_11.setObjectName("config_label_11")
                self.horizontalLayout_15.addWidget(self.config_label_11)
                self.userName = QtWidgets.QLineEdit(self.widget_32)
                self.userName.setMinimumSize(QtCore.QSize(300, 35))
                self.userName.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.userName.setStyleSheet("QLineEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }\n"
                "\n"
                "        QLineEdit:hover {\n"
                "            background-color: #e0e0e0;\n"
                "        }\n"
                "\n"
                "        QLineEdit:focus {\n"
                "            background-color: #ffffff;\n"
                "            border: 2px solid #007bff;\n"
                "        }")
                self.userName.setObjectName("userName")
                self.horizontalLayout_15.addWidget(self.userName)
                self.verticalLayout_9.addWidget(self.widget_32)
                self.widget_33 = QtWidgets.QWidget(self.widget_9)
                self.widget_33.setMinimumSize(QtCore.QSize(0, 40))
                self.widget_33.setMaximumSize(QtCore.QSize(16777215, 40))
                self.widget_33.setObjectName("widget_33")
                self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_33)
                self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_16.setSpacing(3)
                self.horizontalLayout_16.setObjectName("horizontalLayout_16")
                self.config_label_12 = QtWidgets.QLabel(self.widget_33)
                self.config_label_12.setMinimumSize(QtCore.QSize(120, 35))
                self.config_label_12.setMaximumSize(QtCore.QSize(100, 16777215))
                self.config_label_12.setStyleSheet("QLabel {\n"
                "            background-color:#612d26;\n"
                "            font-weight: bold;\n"
                "            color: rgb(255, 255, 255);\n"
                "            padding: 3px;\n"
                "            border-radius: 4px;\n"
                "        }")
                self.config_label_12.setObjectName("config_label_12")
                self.horizontalLayout_16.addWidget(self.config_label_12)
                self.cpf = QtWidgets.QLineEdit(self.widget_33)
                self.cpf.setMinimumSize(QtCore.QSize(300, 35))
                self.cpf.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.cpf.setStyleSheet("QLineEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }\n"
                "\n"
                "        QLineEdit:hover {\n"
                "            background-color: #e0e0e0;\n"
                "        }\n"
                "\n"
                "        QLineEdit:focus {\n"
                "            background-color: #ffffff;\n"
                "            border: 2px solid #007bff;\n"
                "        }")
                self.cpf.setObjectName("cpf")
                self.horizontalLayout_16.addWidget(self.cpf)
                self.verticalLayout_9.addWidget(self.widget_33)
                self.widget_34 = QtWidgets.QWidget(self.widget_9)
                self.widget_34.setMinimumSize(QtCore.QSize(0, 40))
                self.widget_34.setMaximumSize(QtCore.QSize(16777215, 40))
                self.widget_34.setObjectName("widget_34")
                self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_34)
                self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_17.setSpacing(3)
                self.horizontalLayout_17.setObjectName("horizontalLayout_17")
                self.config_label_13 = QtWidgets.QLabel(self.widget_34)
                self.config_label_13.setMinimumSize(QtCore.QSize(120, 35))
                self.config_label_13.setMaximumSize(QtCore.QSize(100, 16777215))
                self.config_label_13.setStyleSheet("QLabel {\n"
                "            background-color:#612d26;\n"
                "            font-weight: bold;\n"
                "            color: rgb(255, 255, 255);\n"
                "            padding: 3px;\n"
                "            border-radius: 4px;\n"
                "        }")
                self.config_label_13.setObjectName("config_label_13")
                self.horizontalLayout_17.addWidget(self.config_label_13)
                self.nascimento = QtWidgets.QLineEdit(self.widget_34)
                self.nascimento.setMinimumSize(QtCore.QSize(300, 35))
                self.nascimento.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.nascimento.setStyleSheet("QLineEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }\n"
                "\n"
                "        QLineEdit:hover {\n"
                "            background-color: #e0e0e0;\n"
                "        }\n"
                "\n"
                "        QLineEdit:focus {\n"
                "            background-color: #ffffff;\n"
                "            border: 2px solid #007bff;\n"
                "        }")
                self.nascimento.setObjectName("nascimento")
                self.horizontalLayout_17.addWidget(self.nascimento)
                self.verticalLayout_9.addWidget(self.widget_34)
                self.widget_35 = QtWidgets.QWidget(self.widget_9)
                self.widget_35.setMinimumSize(QtCore.QSize(0, 40))
                self.widget_35.setMaximumSize(QtCore.QSize(16777215, 40))
                self.widget_35.setObjectName("widget_35")
                self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_35)
                self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_18.setSpacing(3)
                self.horizontalLayout_18.setObjectName("horizontalLayout_18")
                self.config_label_14 = QtWidgets.QLabel(self.widget_35)
                self.config_label_14.setMinimumSize(QtCore.QSize(120, 35))
                self.config_label_14.setMaximumSize(QtCore.QSize(100, 16777215))
                self.config_label_14.setStyleSheet("QLabel {\n"
                "            background-color:#612d26;\n"
                "            font-weight: bold;\n"
                "            color: rgb(255, 255, 255);\n"
                "            padding: 3px;\n"
                "            border-radius: 4px;\n"
                "        }")
                self.config_label_14.setObjectName("config_label_14")
                self.horizontalLayout_18.addWidget(self.config_label_14)
                self.senha = QtWidgets.QLineEdit(self.widget_35)
                self.senha.setMinimumSize(QtCore.QSize(300, 35))
                self.senha.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.senha.setStyleSheet("QLineEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }\n"
                "\n"
                "        QLineEdit:hover {\n"
                "            background-color: #e0e0e0;\n"
                "        }\n"
                "\n"
                "        QLineEdit:focus {\n"
                "            background-color: #ffffff;\n"
                "            border: 2px solid #007bff;\n"
                "        }")
                self.senha.setObjectName("senha")
                self.horizontalLayout_18.addWidget(self.senha)
                self.verticalLayout_9.addWidget(self.widget_35)
                self.inObs_2 = QtWidgets.QTextEdit(self.widget_9)
                self.inObs_2.setObjectName("inObs_2")
                self.verticalLayout_9.addWidget(self.inObs_2)
                self.widget_11 = QtWidgets.QWidget(self.widget_9)
                self.widget_11.setMinimumSize(QtCore.QSize(0, 53))
                self.widget_11.setMaximumSize(QtCore.QSize(16777215, 80))
                self.widget_11.setStyleSheet("QWidget {\n"
                "          \n"
                "            background-color:#92653c;\n"
                "            color: #ffffff;\n"
                "            padding: 8px;\n"
                "            border-radius:20px;\n"
                "        }")
                self.widget_11.setObjectName("widget_11")
                self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_11)
                self.horizontalLayout_19.setObjectName("horizontalLayout_19")
                self.saveUser = QtWidgets.QPushButton(self.widget_11)
                self.saveUser.setMinimumSize(QtCore.QSize(150, 35))
                self.saveUser.setMaximumSize(QtCore.QSize(16777215, 35))
                self.saveUser.setStyleSheet("QPushButton {\n"
                "            background-color: #612d26;\n"
                "            color: #ffffff;\n"
                "            padding: 3px;\n"
                "            border-radius: 12px;\n"
                "        }\n"
                "\n"
                "        QPushButton:hover {\n"
                "            background-color: #3a211d;\n"
                "        }\n"
                "\n"
                "        QPushButton:pressed {\n"
                "            background-color: #8a605a;\n"
                "        }")
                self.saveUser.setObjectName("saveUser")
                self.horizontalLayout_19.addWidget(self.saveUser)

                self.verticalLayout_9.addWidget(self.widget_11)
                self.verticalLayout_7.addWidget(self.widget_9)
                self.horizontalLayout_2.addWidget(self.frame_2)
                self.horizontalLayout_6.addWidget(self.widget_5)
                self.frame = QtWidgets.QFrame(self.widget)
                self.frame.setStyleSheet("QWidget {\n"
                "          \n"
                "            background-color:rgb(255, 226, 127);\n"
                "            color: #ffffff;\n"
                "            padding: 8px;\n"
                "            border-radius:20px;\n"
                "        }")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
                self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_4.setObjectName("verticalLayout_4")
                self.widget_7 = QtWidgets.QWidget(self.frame)
                self.widget_7.setMinimumSize(QtCore.QSize(50, 0))
                self.widget_7.setMaximumSize(QtCore.QSize(16777215, 50))
                self.widget_7.setObjectName("widget_7")
                self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_7)
                self.verticalLayout_5.setContentsMargins(0, 0, 0, -1)
                self.verticalLayout_5.setObjectName("verticalLayout_5")
                self.label_2 = QtWidgets.QLabel(self.widget_7)
                self.label_2.setObjectName("label_2")
                self.verticalLayout_5.addWidget(self.label_2)
                self.verticalLayout_4.addWidget(self.widget_7)
                self.widget_4 = QtWidgets.QWidget(self.frame)
                self.widget_4.setMinimumSize(QtCore.QSize(0, 200))
                self.widget_4.setSizeIncrement(QtCore.QSize(0, 0))
                self.widget_4.setObjectName("widget_4")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
                self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.pushButton_2.setText("")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap(".\\ui\\../images/shopOnline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.pushButton_2.setIcon(icon1)
                self.pushButton_2.setIconSize(QtCore.QSize(150, 150))
                self.pushButton_2.setObjectName("pushButton_2")
                self.verticalLayout_3.addWidget(self.pushButton_2)
                self.verticalLayout_4.addWidget(self.widget_4)
                self.widget_6 = QtWidgets.QWidget(self.frame)
                self.widget_6.setObjectName("widget_6")
                self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_6)
                self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_6.setSpacing(9)
                self.verticalLayout_6.setObjectName("verticalLayout_6")
                self.widget_31 = QtWidgets.QWidget(self.widget_6)
                self.widget_31.setMinimumSize(QtCore.QSize(0, 40))
                self.widget_31.setMaximumSize(QtCore.QSize(16777215, 40))
                self.widget_31.setObjectName("widget_31")
                self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_31)
                self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_13.setSpacing(3)
                self.horizontalLayout_13.setObjectName("horizontalLayout_13")
                self.config_label_10 = QtWidgets.QLabel(self.widget_31)
                self.config_label_10.setMinimumSize(QtCore.QSize(120, 35))
                self.config_label_10.setMaximumSize(QtCore.QSize(100, 16777215))
                self.config_label_10.setStyleSheet("QLabel {\n"
                "            background-color:#612d26;\n"
                "            font-weight: bold;\n"
                "            color: rgb(255, 255, 255);\n"
                "            padding: 3px;\n"
                "            border-radius: 4px;\n"
                "        }")
                self.config_label_10.setObjectName("config_label_10")
                self.horizontalLayout_13.addWidget(self.config_label_10)
                self.nomeFantasia = QtWidgets.QLineEdit(self.widget_31)
                self.nomeFantasia.setMinimumSize(QtCore.QSize(300, 35))
                self.nomeFantasia.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.nomeFantasia.setStyleSheet("QLineEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }\n"
                "\n"
                "        QLineEdit:hover {\n"
                "            background-color: #e0e0e0;\n"
                "        }\n"
                "\n"
                "        QLineEdit:focus {\n"
                "            background-color: #ffffff;\n"
                "            border: 2px solid #007bff;\n"
                "        }")
                self.nomeFantasia.setObjectName("nomeFantasia")
                self.horizontalLayout_13.addWidget(self.nomeFantasia)
                self.verticalLayout_6.addWidget(self.widget_31)
                self.widget_30 = QtWidgets.QWidget(self.widget_6)
                self.widget_30.setMinimumSize(QtCore.QSize(0, 40))
                self.widget_30.setMaximumSize(QtCore.QSize(16777215, 40))
                self.widget_30.setObjectName("widget_30")
                self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_30)
                self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_12.setSpacing(3)
                self.horizontalLayout_12.setObjectName("horizontalLayout_12")
                self.config_label_9 = QtWidgets.QLabel(self.widget_30)
                self.config_label_9.setMinimumSize(QtCore.QSize(120, 35))
                self.config_label_9.setMaximumSize(QtCore.QSize(100, 16777215))
                self.config_label_9.setStyleSheet("QLabel {\n"
                "            background-color:#612d26;\n"
                "            font-weight: bold;\n"
                "            color: rgb(255, 255, 255);\n"
                "            padding: 3px;\n"
                "            border-radius: 4px;\n"
                "        }")
                self.config_label_9.setObjectName("config_label_9")
                self.horizontalLayout_12.addWidget(self.config_label_9)
                self.cnpj = QtWidgets.QLineEdit(self.widget_30)
                self.cnpj.setMinimumSize(QtCore.QSize(300, 35))
                self.cnpj.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.cnpj.setStyleSheet("QLineEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }\n"
                "\n"
                "        QLineEdit:hover {\n"
                "            background-color: #e0e0e0;\n"
                "        }\n"
                "\n"
                "        QLineEdit:focus {\n"
                "            background-color: #ffffff;\n"
                "            border: 2px solid #007bff;\n"
                "        }")
                self.cnpj.setObjectName("cnpj")
                self.horizontalLayout_12.addWidget(self.cnpj)
                self.verticalLayout_6.addWidget(self.widget_30)
                self.descricao = QtWidgets.QTextEdit(self.widget_6)
                self.descricao.setStyleSheet("QTextEdit {\n"
                "            background-color: #f0f0f0;\n"
                "            border: none;\n"
                "            padding: 2px;\n"
                "            border-radius: 4px;\n"
                "            color: #333;\n"
                "            font-size:13px\n"
                "        }")
                self.descricao.setObjectName("descricao")
                self.verticalLayout_6.addWidget(self.descricao)
                self.widget_10 = QtWidgets.QWidget(self.widget_6)
                self.widget_10.setMinimumSize(QtCore.QSize(0, 50))
                self.widget_10.setMaximumSize(QtCore.QSize(16777215, 80))
                self.widget_10.setStyleSheet("QWidget {\n"
                "          \n"
                "            background-color:#92653c;\n"
                "            color: #ffffff;\n"
                "            padding: 8px;\n"
                "            border-radius:20px;\n"
                "        }")
                self.widget_10.setObjectName("widget_10")
                self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_10)
                self.horizontalLayout_14.setObjectName("horizontalLayout_14")
                self.saveShop = QtWidgets.QPushButton(self.widget_10, clicked=lambda : self.__saveShopInfo())
                self.saveShop.setMinimumSize(QtCore.QSize(150, 35))
                self.saveShop.setMaximumSize(QtCore.QSize(16777215, 35))
                self.saveShop.setStyleSheet("QPushButton {\n"
                "            background-color: #612d26;\n"
                "            color: #ffffff;\n"
                "            padding: 3px;\n"
                "            border-radius: 12px;\n"
                "        }\n"
                "\n"
                "        QPushButton:hover {\n"
                "            background-color: #3a211d;\n"
                "        }\n"
                "\n"
                "        QPushButton:pressed {\n"
                "            background-color: #8a605a;\n"
                "        }")
                self.saveShop.setObjectName("saveShop")
                self.horizontalLayout_14.addWidget(self.saveShop)

                self.homeButton = QtWidgets.QPushButton(self.widget_10, clicked=lambda: self.__backHome())
                self.homeButton.setMinimumSize(QtCore.QSize(150, 35))
                self.homeButton.setMaximumSize(QtCore.QSize(16777215, 35))
                self.homeButton.setText("HOME")
                self.homeButton.setStyleSheet("QPushButton {\n"
                                            "            background-color: #612d26;\n"
                                            "            color: #ffffff;\n"
                                            "            padding: 3px;\n"
                                            "            border-radius: 12px;\n"
                                            "        }\n"
                                            "\n"
                                            "        QPushButton:hover {\n"
                                            "            background-color: #3a211d;\n"
                                            "        }\n"
                                            "\n"
                                            "        QPushButton:pressed {\n"
                                            "            background-color: #8a605a;\n"
                                            "        }")
                self.homeButton.setObjectName("saveShop")

                self.horizontalLayout_19.addWidget(self.homeButton)

                self.verticalLayout_6.addWidget(self.widget_10)
                self.verticalLayout_4.addWidget(self.widget_6)
                self.horizontalLayout_6.addWidget(self.frame)
                self.verticalLayout.addWidget(self.widget)

                self.retranslateUi(Form)
                QtCore.QMetaObject.connectSlotsByName(Form)

                self.broadcast = broadcast.Broadcast()
                self.oracleBD = connection_db.Oracle_db()

                self.__initLabels()

        def retranslateUi(self, Form):
                _translate = QtCore.QCoreApplication.translate
                Form.setWindowTitle(_translate("Form", "Form"))
                self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">DADOS DO USUÁRIO</span></p></body></html>"))
                self.config_label_11.setText(_translate("Form", "NOME"))
                self.config_label_12.setText(_translate("Form", "CPF"))
                self.config_label_13.setText(_translate("Form", "NASCIMENTO"))
                self.config_label_14.setText(_translate("Form", "NOVA SENHA"))
                self.saveUser.setText(_translate("Form", "SALVAR"))
                self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">DADOS DA LOJA</span></p></body></html>"))
                self.config_label_10.setText(_translate("Form", "NOME FANTASIA"))
                self.config_label_9.setText(_translate("Form", "CNPJ"))
                self.saveShop.setText(_translate("Form", "SALVAR"))




        def __saveShopInfo(self):

                cpf = self.broadcast.credentials()["CPF"]
                nomeFantasia = self.nomeFantasia.text()
                cnpj = self.cnpj.text()
                desc = self.descricao.toPlainText()

                payload = [cpf, nomeFantasia, cnpj, desc]
                self.broadcast.bdData(payload)

                self.oracleBD.setShopInfo()

                self.__initLabels()

        def __initLabels(self):


                payload = self.broadcast.credentials()

                self.userName.setText(payload["NAME"])
                self.cpf.setText(payload["CPF"])
                self.nascimento.setText(payload["AGE"])

                cpf = payload["CPF"]
                payload = [cpf]

                self.broadcast.bdData(payload)
                self.oracleBD.getShopInfo()

                response = self.broadcast.dataTransfer()

                if response != False and response != None:

                        self.nomeFantasia.setText(str(response[2]))
                        self.cnpj.setText(str(response[3]))
                        self.descricao.setText(response[4])


        def __backHome(self):
                self.stackedWidget.setCurrentIndex(2)

